tweetme/tweetme/settings/advcbv/advcbv/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$',views.index),
    url(r'^$',views.IndexView.as_view()),
    url(r'^basic_app/',include('basic_app.urls',namespace='basic_app')),

]

tweetme/tweetme/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from tweets.views import TweetListView

from .views import home,aboutme
from accounts.views import UserRegisterView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^about-me/',aboutme,name="about"),
    url(r'^$',TweetListView.as_view(),name="home"),
    url(r'^profiles/',include('accounts.urls',namespace="accounts")),
    url(r'^register/$', UserRegisterView.as_view(), name='register'),
    url(r'^posts/',include('tweets.urls',namespace="tweets_app")),
    url(r'^api/tweet',include('tweets.api.urls',namespace="tweet-api")),
    url(r'^', include('django.contrib.auth.urls')),
]

# 
# if settings.DEBUG:
#     urlpatterns+=(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

tweetme/tweets/api/urls.py
from django.conf.urls import url
from .views import TweetListAPIView
from django.views.generic.base import RedirectView
urlpatterns=[
    url(r'^$',TweetListAPIView.as_view(),name='list'),

]

tweetme/tweets/urls.py
from django.conf.urls import url
from .views import TweetDetailview, TweetListView, TweetCreateView, TweetUpdateView, TweetDeleteView
from django.views.generic.base import RedirectView
urlpatterns=[
    url(r'^$',RedirectView.as_view(url='/')),
    url(r'^search/$',TweetListView.as_view(),name='list'),
    url(r'^(?P<pk>\d+)/$',TweetDetailview.as_view(),name='detail'),
    url(r'^create/$',TweetCreateView.as_view(),name='create'),
    url(r'^(?P<pk>\d+)/update/$',TweetUpdateView.as_view(),name='update'),
    url(r'^(?P<pk>\d+)/delete/$',TweetDeleteView.as_view(),name='delete')

]

tweetme/tweets/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from .validators import restrictmodel
from django.urls import reverse
from django.utils.timesince import timesince
# from django.contrib.auth import get_user_model
# # Create your models here.
# 
# User = get_user_model()


class Tweet(models.Model):
    user        = models.ForeignKey(settings.AUTH_USER_MODEL,default=1)
    content     = models.CharField(max_length=140,validators=[restrictmodel])
    timestamp   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse('tweets_app:detail', kwargs={"pk":self.pk})
    # Models one way of validation which can be declared in class
    def clean(self,*args,**kwargs):
        content=self.content
        if content=='sarath':
            raise ValidationError("Dont enter ur name")
        return super(Tweet,self).clean(*args,**kwargs)


    class Meta:
        ordering = ['-timestamp','content']

tweetme/tweets/forms.py
from django import forms
from .models import Tweet

class TweetModelForm(forms.ModelForm):
    content = forms.CharField(label='',
                widget=forms.Textarea(
                        attrs={'placeholder': "Your message",
                            "class": "form-control","maxlength":"140"}
                    ))
    class Meta:
        model=Tweet
        fields = [
            # "user",
            "content"
        ]
    #we can define validators in forms or in models itself
    #clean_(formfield) is defined
    def clean_content(self,*args,**kwargs):
        content = self.cleaned_data.get("content")
        if content == 'abc':
            raise forms.ValidationError("Dont enter abc")
        return content

tweetme/tweets/api/views.py
from rest_framework import generics
from .serializers import TweeetModelSerializer
from tweets.models import Tweet

class TweetListAPIView(generics.ListAPIView):
    serializer_class = TweeetModelSerializer
    def get_queryset(self):
        return Tweet.objects.all()

tweetme/tweets/views.py
from django.shortcuts import render
from tweets.models import Tweet
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from .forms import TweetModelForm
from .mixins import FormUserNeededMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

#
class TweetListView(LoginRequiredMixin,ListView):
    template_name="tweets/list_view.html"
    #queryset=Tweet.objects.all()
    def get_queryset(self,*args,**kwargs):
        qs =  Tweet.objects.all()
        # print (self.request.GET)    #dict with what we have searched  {'q':'search_text'}
        query = self.request.GET.get("q",None)
        if query is not None:
            qs=qs.filter(Q(content__icontains=query) |
                         Q(user__username__icontains=query))
        paginator = Paginator(qs, 10) # Show 25 contacts per page
        page_request_var = "page"
        page = self.request.GET.get(page_request_var)
        try:
            qs = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            qs = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            qs = paginator.page(paginator.num_pages)
        return qs

    def get_context_data(self,*args,**kwargs):
        obj = super(TweetListView,self).get_context_data(*args,**kwargs)
        obj['create_form']  = TweetModelForm()
        obj['create_url']   = reverse_lazy('tweets_app:create')
        #print (obj)
        return obj



    # columns=[field.name for field in Tweet._meta.get_fields()]
    # print(columns)
    # obj=Tweet()
    # obj.content='Hello wvwry one'
    # obj.save()

class TweetDetailview(DetailView):
    queryset=Tweet.objects.all()
    template_name="tweets/detailed_view.html"
    # def get_object(self):
    #     print (self.kwargs)
    #     pk=self.kwargs.get("pk")
    #     print (pk)
    #     return Tweet.objects.get(id=pk)


class TweetCreateView(FormUserNeededMixin,LoginRequiredMixin,CreateView):
    form_class = TweetModelForm
    template_name = "tweets/create_view.html"
    # If we are not redirecting output to any url it will user getabsoluteurl function defined in models
    # success_url='/tweet/create/'
    login_url = '/login/'
    success_url = '/'

class TweetUpdateView(LoginRequiredMixin,UpdateView):
    queryset=Tweet.objects.all()
    form_class = TweetModelForm
    template_name = "tweets/update_view.html"
    success_url='/tweet/'

class TweetDeleteView(DeleteView):
    model = Tweet # or queryset=Tweet.objects.all()
    success_url=reverse_lazy("tweets_app:list")  #namespace : name
    template_name="tweets/delete_confirm.html"

tweetme/tweets/templates/tweets/aboutme.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{%block title%}Tweet{% endblock title%}</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">MessageMart</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      {% if request.user.is_authenticated %}
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'about'%}">About</a></li>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu"> -->
            <li><a href="{% url 'logout' %}">Logout</a></li>

          </ul>
        </li>
      </ul>
      {% else %}
      <ul>
        <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'login' %}">Login</a></li>
        <li><a href="{% url 'register' %}">Register</a></li>
      </ul>
      {% endif %}
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

</div>


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<div class="container">
  <div class="row">
    <div class="container">
      <div class="jumbotron">
        <h2>AboutMe:</h2>
        <h3>Hi I am Sarathchandra from Andhra Pradesh, graduated at Amrita School Of Engineering.</h3>
        <ul>
          <li>Proficient in technical aspects like Data structures,Algorithms.</li>
          <li>Excellent skills in Full-Stack development,Database Management,AWS cloud platform</li>
          <li>Proficient at building and managing professional relationships.</li>
          <li>Definite abilities in leadership,planning,and decision making.</li>
        </ul>

        <h2>MessageMart</h2>
        <ul>
          <li>Develeoped this website with Django, Bootstrap, jQuery, Django REST framework and its main functionality is to share your ideas and thoughts.</li>
          <li>Feel free to login and post your thoughts.</li>
        </ul>

        <h2><center>THANK TOU...</center></h2>


    </div>


    </div>


  </div>

</div>
</body>
</html>

tweetme/tweets/templates/tweets/create_view.html
{% extends "base.html"%}
{% block content %}
<h1>Create Tweet</h1>
{% include "tweets/form.html" with form=form btn_title='Tweet' %}

{% endblock content %}

tweetme/tweets/templates/tweets/delete_confirm.html
{% extends "base.html"%}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock content %}

tweetme/tweets/templates/tweets/detailed_view.html
{% extends "base.html"%}
{% block content %}

{% load static %}
<div class="row">
  <div class="col-sm-3">
    <h1>{{request.user}}</h1>
  </div>
  <div class="col-xs-9">
    {{ object.content }}<br><hr>
    <!-- {{ object.user }}<br>
    {{ object.timestamp }}<br>
    {{ object.timestamp|timesince }} -->
  </div>

</div>


{% endblock content %}

tweetme/tweets/templates/tweets/form.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form method="post" action="{% if action_url %}{{ action_url }}{% endif %}" class='form'>
      {{ form.as_p }}
      {% csrf_token %}

      <input class="btn btn-primary" type="submit" value="{{ btn_title }}" /> <span id="chars">140</span>

    </form>
  </body>
</html>

tweetme/tweets/templates/tweets/list_view.html
{% extends "base.html" %}
 {% block script %}
<script type="text/javascript">
var maxLength = 140;
$('textarea').keyup(function() {
var length = $(this).val().length;
var length = maxLength-length;
$('#chars').text(length);
});
</script>
{% endblock script %}
{% block content %}



    <div class='row'>
      <div class='col-sm-3'>
        <h1 ><a href='{% url "accounts:detail" username=request.user %}'>{{ request.user }}</a></h1>
        <hr>
      </div>
        <div class='col-sm-9'>
          {% if not request.GET.q %}
          <div class="row">
            {% include "tweets/form.html" with form=create_form action_url=create_url btn_title="Post" %}
          </div>
          {%endif%}
          <hr>
        {% for object in object_list %}
            <div class="media">
                  <div class="media-left">
                    <a href="#">
                      {% if object.image %}
                        <img class="media-object" src="..." alt="...">
                     {% endif %}
                    </a>
                  </div>
                  <div class="media-body">
                    {{ object.content }}<br/>
                    via <a href='{% url "accounts:detail" username=object.user %}'>{{ object.user }}</a> | {{ object.timestamp|timesince }} ago | {{object.updated}} |
                     <a href='{{ object.get_absolute_url }}'>View</a>
                      {% if request.user == object.user %}
                     | <a href='{% url "tweets_app:delete" pk=object.pk%}'>Delete</a>
                     {%endif%}

                  </div>
            </div>
            <hr/>
        {% empty %}
            {% if request.GET.q %}
             <p>No tweets found.</p>
            {% else %}
            <p>No tweets yet.</p>
            {% endif %}
        {% endfor %}
        </div>
<!--  -->

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ object_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?page={{ object_list.next_page_number }}">next</a>
            <a href="?page={{ object_list.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
<!--  -->


    </div>


{% endblock content %}

tweetme/tweets/templates/tweets/search_form.html
<form class="navbar-form navbar-left" method='GET' action='{% url "tweets_app:list" %}'>
       <div class="form-group">
           <input class="form-control" type='text' name='q' placeholder='Your search' value='{{ request.GET.q }}'/>
           </div>
       <input class="btn btn-default" type='submit' value='Search'/>

</form>

tweetme/tweets/templates/tweets/update_view.html
{% extends "base.html"%}
{% block content %}
{% include "tweets/form.html" with form=form btn_title='Update' %}

{% endblock content %}